[build]
  base = "clients/web"
  publish = "dist/web"
  command = "ng build --configuration production --no-extract-css --no-inline-style"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
